version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - FLASK_ENV='development'
    volumes:
      - .:/code/:z
    command: >
      bash -c "flask run --host=0.0.0.0"
    ports:
      - "5000:5000"